---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
passphrase: virtusa-ms-labs
---
spring:
  profiles: FundTransfer
words: selfaccount, interbank, intrabank

---
spring:
  profiles: BalanceCheck
words: inUSD
