---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

logging:
  file: C:\Temp\spring-boot-logs/net.vai.labs.log
passphrase : virtusa-ms-labs
